### PR TITLE
Compliance with CiviCRM 4.7/5.x

### PR DESCRIPTION
**Pull request by VangelisP**
This is a small commit that normalizes files through `civix generate:module` plus a small addition of an `if` statement during the group creation that was causing some notices in the logs.

### CODE REVIEW

**Comment by sluc23** [comment]
hi @davidknoll is this extension still active / maintained by you?
Would you consider accepting this PR or do we start our own fork? tx!

**Comment by JohnFF** [comment]
@davidknoll I've reviewed and support a merge :)

**Comment by davidknoll** [comment]
Consider it merged. As I mentioned though, I haven't tested it.

@johnff I'm going to ask Laura if she's OK with me giving you control of our public Civi stuff, since we're not using it any more. Are you interested?

**Comment by sluc23** [comment]
thanks @davidknoll  , yes we will interested on.
We are not heavy users of this extensions but we use it in a couple of websites, and we might take care of having it updated.

cheers!

**Comment by JohnFF** [comment]
Yes please :)

But also, we should consider who it makes most sense to continue to be 
maintainers for this project. Are you still interested in being the 
owner? If not, maybe if sluc was to fork it and make him & his team the 
primary maintainer that'd be best.

**Comment by sluc23** [comment]
if you agree, we can fork this extension and put it under `lab.c.o/extensions/splitgroup`
we are moving all our public extensions there, and we can add you as well as co-maintainers if you want to 

thanks for your feedback on this!

**Comment by davidknoll** [comment]
@sluc23 Sorry for leaving this alone for so long. I am happy for you to take over this extension officially. We have another extension that I have just been contacted about. If you're still interested, please confirm whether I need to do anything with updating the extensions directory.

**Pull request merged**
